### ISSUE TITLE
Disable auto update check

### ISSUE THREAD

**Issue by ask2018** [DukeLupus/dlFilter#43]
I'm using dlFilter on network from where update server is never reachable. So I have there just the annoying messages about update check failed. It's possible to add "Never check for updates" settings in the updates?

**Comment by Sophist-UK** [comment]
Yes.

**Comment by Sophist-UK** [comment]
Is this an issue with it not supporting Proxy / Socks for update checks or is it absolutely unreachable?

**Comment by ask2018** [comment]
Issue with not supporting socks proxy. But even if you fix that, still "Never check for updates" settings would be nice. Some people as me simply have strict firewall rules based on only few specific IP/ports allowed per application and prefer to check for updates manually if needed and not adding unneeded ranges and ports for all software into the firewall rules. For now I've just deleted the update check part from the code as temp solution for me, so there is no rush on this issue from my side.

**Comment by Sophist-UK** [comment]
I have created PR #55 to provide an option to enable / disable updated checks.

You can download this for testing from https://raw.githubusercontent.com/DukeLupus/dlFilter/11e044456519933ea9c9c92a2651b952ef001428/dlFilter.mrc

Please test it and give us feedback.

If you would be willing to test a SOCKS4/5/Proxy solution (even though you don't want to run update checks) that would be very helpful.

**Comment by ask2018** [comment]
Sorry for late reply. I was not around last week. Testing it now and "enable / disable updated checks" option works fine for me. Thanks for adding it.

SOCKS4/5/Proxy solution - I can test it, but I don't see there any new option for adding proxy inside dlFilter settings and if it should auto grab proxy from MIRC settings, then it doesn't work.
If I keep the updates enabled. It just tries to access the update server directly and returns error, because my firewall blocks it.
(09:49:58) [dlFilter] Checking for dlFilter updates...
(09:49:58) [dlFilter] Error: DLF.Socket.Update: https://raw.githubusercontent.com/DukeLupus/dlFilter/master/dlFilter.version: connecting: Failed to establish socket connection: [10013] Permission denied

**Comment by Sophist-UK** [comment]
I haven't coded for Socks yet. My plan (when I get time) is to query the mIRC socks settings and use those automatically. I will need someone to test it once it is coded.

I will merge this PR now.

**Comment by Sophist-UK** [comment]
Fixed by #53.

**Comment by ask2018** [comment]
Ok I can test it when done.
