### ISSUE TITLE
Insufficient parameters.

### ISSUE THREAD

**Issue by blindndangerous** [DukeLupus/dlFilter#49]
I'm unsure if this has been reported before, so if it has, my apologies.  Using Adiirc, and the latest dlfilter from github, I see this. I'm not sure what's causing it to happen either.
* /if: insufficient parameters (line 5149, dlFilter.mrc)

**Comment by Sophist-UK** [comment]
I will take a look at this, however dlFilter is not (yet) tested or supported on Adiirc.

**Comment by Sophist-UK** [comment]
However, happy to accept PRs from you to make it work on Adiirc.

**Comment by Sophist-UK** [comment]
Closing this as AdiIRC is not (yet) supported.
