### ISSUE TITLE
Ads window has op/voice flags, but...

### ISSUE THREAD

**Issue by Sophist-UK** [DukeLupus/dlFilter#50]
1. They are not adding much value; and
2. They are not being updated when op / voice status changes.

Suggest that they are removed from the Ads window.

**Comment by SanderSade** [comment]
On the other hand, it is a handy feature to see if server is voiced - and possibly detect dodgy servers. I am not sure how that feature is used, though

**Comment by Sophist-UK** [comment]
Ok - going to close this.
