### ISSUE TITLE
Issue with options dialog when Windows Display scaling > 100% 

### ISSUE THREAD

**Issue by cstantech** [DukeLupus/dlFilter#72]
The tab opens but its compacted so I cannot see anything and I am unable to widen the window to seem more to change any settings for the filter.
I thought it might be my display settings since this system is a 4k display so I tried a 1024 x 768 but its still not working and yes I even tried the latest dlfilter and the same problem.

**Comment by Sophist-UK** [comment]
I suspect that this is an issue of mIRC on 4k screens and dialogs. It is possible that there are some dialog settings that I can fix or mIRC setttings that you can change, or you might need to try setting Windows 10 Settings / System / Display / Custom Scaling to see if that helps (even temporarily as it may have other consequence on how stuff looks on your 4K display).

1. We need screen shots to see what you mean.

2. What version of mIRC are you running? Ditto Windows? Also (just in case it is a driver issue) please advise what screen it is and what your graphics card and drivers are.

**Comment by Sophist-UK** [comment]
P.S. Can you also please run the following command on mIRC on your 4K display and on your 1024 x 768 display and post the results here:

`//echo -ac Normal DBU Width: $dbuw DBU Height: $dbuh`

**Comment by Sophist-UK** [comment]
OK - I have checked what mIRC says about showing dialogs at a consistent size regardless of screen pixel size (Use `Option dbu`) and we already do that. So this seems likely to be a mIRC issue. Please send me the info I have asked for and I will pursue it.

**Comment by Sophist-UK** [comment]
Does this only happen when you right-click and choose options or also when you use menu Commands / dlFilter / Options?

**Comment by cstantech** [comment]
https://ibb.co/kbmfq9

**Comment by cstantech** [comment]
Yes when I right click and click on options.
The smaller window for the options for the filter is completely inert with only minimize and close working.

**Comment by Sophist-UK** [comment]
The Options dialog is not resizeable - mIRC dialogs are fixed size.

Please post picture of mIRC and dialog box on a lower resolution screen, and provide all the other information requested.

**Comment by cstantech** [comment]
Windows 10 pro on a dell 7559 i5 cpu and latest version of mirc and here is a pic with windows set to 1024x768 https://ibb.co/nmuJee

**Comment by Sophist-UK** [comment]
Please provide screen shot WITH dialog showing.

Please provide all information requested.

**Comment by Sophist-UK** [comment]
P.S. I am giving up my time to try to work with you on this even though it is a mIRC problem rather than with my script, and I am both disappointed and frustrated with the slow responses and lack of information. Without this information I cannot work with the author of mIRC to get this fixed and will then have to close this issue unresolved.

**Comment by cstantech** [comment]
The second screenshot i posted already has the results from the //echo -ac Normal width $window(-1).w height $window(-1).h / dbuw $dbuw dbuh $dbuh 
Unless of course I did something wrong (would not be the first time) as for changing resolution including scaling it had zero effect as far as allowing me to view the contents of the options tab.

**Comment by Sophist-UK** [comment]
1. Please post output from the `//echo -ac Normal width $window(-1).w height $window(-1).h / dbuw $dbuw dbuh $dbuh` as text.

2. Please run it on both 4K and 1024x768.

3. Please post a screen shot of the dialog box on 1024x768.

4. Please post details of your graphics card and graphics driver versions.

**Comment by Sophist-UK** [comment]
5. Please post details of your Windows 10 version i.e. 1703 / 1709 / 1803 etc. and your Windows Settings / System / Display / Scale (Change the size of text, apps and other items).

**Comment by Sophist-UK** [comment]
P.S. At this point it appears that I think this issue is worth fixing more than the OP does. If I don't get the information I need in the next day or so, I am going to close this issue and stop trying to help.

**Comment by Sophist-UK** [comment]
7. Please edit the dlFilters script and go to c. line 3715 and change
```
option dbu notheme
```
to:
```
option dbu
```
and see if it makes any difference to the dialog / font sizes.

**Comment by cstantech** [comment]
4K below
width 3840 height 2160 / dbuw 2.5 dbuh 2.5 
1024x768 below with link to a link to pic of the the options tab (which is what I assume you meant when you asked for the dialog if not please do not shoot me) 
width 2560 height 1920 / dbuw 2.5 dbuh 2.5
https://ibb.co/cppDze

Laptop has two video cards an Intel HD 530 driver version 23.20.16.4973 as well as a Nvidia GTX 960M driver version 24.21.13.9882
I tried editing the file as per your request and nothing changed there also.
I think I will try a complete uninstall of mirc now followed by cleaning my registry and then reboot and reinstall an older one and try the script then because the only thing thats changed with the system other than some drivers in the past year was I updated Mirc itself to the newest version.
My apologies for being such a hassle to deal with also but I do want to say I do appreciate your efforts to help me Sophist-UK.

**Comment by cstantech** [comment]
Update:
Downgraded  to older 6.35 version of and installed filter and the filter works perfect but as soon as I upgrade Mirc to the newest version its back to being unable to access the options tab however if I downgrade to the older version as soon as I downgrade it will allow me to access all the options clear as day.

**Comment by Sophist-UK** [comment]
Thanks for the extra information, but this is your last chance to do as I ask before I close this:

Req 1. / 2. Please post output from the `//echo -ac Normal width $window(-1).w height $window(-1).h / dbuw $dbuw dbuh $dbuh` as text at 1024x768. 

Req 2. Please post a screen shot of the dialog box on 1024x768.

Req 5. Please post details of your Windows 10 version i.e. 1703 / 1709 / 1803 etc. and your Windows Settings / System / Display / Scale (Change the size of text, apps and other items).

Req 6. Have you adjusted your windows theme font sizes or your mIRC fonts instead of using display scaling as in 5.?

Also:

Req 7. Please state which graphics card mIRC is using.

Req 8. Please state whether you are using Windows screen resolution to downgrade the resolution to 1024x768 or whether you have a separate screen with 1024x768 as native.

**Comment by cstantech** [comment]
I think I might have figured out what was happening.
 I had set it as you requested to the resolution of 1024x768 in windows and it was giving me the results I posted above and when then I set it to 800x600 again via windows it gave me width 2000 height 1500 / dbuw 2.5 dbuh 2.5 in Mirc.
That got me thinking.......what if it was an issue with the nvidia gpu? I mean sure its not the primary gpu but its still part of the system so I checked the driver options via the nvidia control panel and saw that the option for Global Settings tab under Preferred Graphics Card it was set to the nvidia card so when I changed it  to automatic and rebooted the filter loaded properly in Mirc.

**Comment by Sophist-UK** [comment]
Ok - so it is working on Intel graphics but not on nVidia. If your laptop is anything like mine, then you want default graphics to be intel in order to preserve battery life.

We can also see something happening here:

You set resolution to 800x600 and it shows 2000x1500 dbu 2.5 - and 2000 is 2.5x 800 and 1500 is 2.5x 600. Similarly, 2560 is 2.5x 1024 and 1920 is 2.5x768.

What happens when you set mIRC to launch on nVidia when default is Intel?

Also, please answer all previous questions in full - so we can try to work out what is going on.

**Comment by Sophist-UK** [comment]
When you give full answers, please describe EXACTLY what screen you are using (model, native resolution, windows resolution, output from the echo command and whether the dialog is correct or squashed.

**Comment by cstantech** [comment]
Well it was working LOL.
I did all that and thought great so installed updated mirc and checked and it was working fine then changed my resolution back to the higher one and rebooted and its back do doing the same thing of being small and unable to access it. Going to change the resolution to the lower one now, reboot for it to take total effect and then run mirc and post the results for that command line.

**Comment by cstantech** [comment]
It looks like its a scaling issue.
Setting it at 100% and then relogging mirc and the filter is fine however if I raise the resolution to max and then allow windows to run its 250%  scaling the filter goes wonkers.
If I keep the resolution but lower the scaling to 100% the filter works fine but its not very usable since everything is so tiny lol
Also I tried raising the scaling slowly and the tab contents of the filter gradually disappear as I raise the scaling.
If you want I will post a screen shot of it set at 100,175 and 200 so you can see though it will take me few  minutes as I will need to relog to have it take effect properly each time I found.

**Comment by Sophist-UK** [comment]
Ok - I have asked several times for full details and you only give general descriptions which are insufficient to diagnose and fix the problem - so I am closing this. If you decide to post full details I may reopen it.

**Comment by Sophist-UK** [comment]
I have now completed testing this and custom scaling breaks mirc dialogs. It is a mIRC bug.

So now closing this issue as it is not fixable by me.

**Comment by SanderSade** [comment]
I wonder if it is worth notifying Khaled/mIRC about this issue? Although, the chances are that it is a known bug, and not worth fixing...

**Comment by Sophist-UK** [comment]
@SanderSade https://forums.mirc.com/ubbthreads.php/topics/263634/Dialog_on_4K_screen

@cstantech Immediate scaling change using dropdowns is not working correctly in Windows 10 1709. After reboot / signout this issue still occurs. On my PC at 125% it is still readable, but that is possibly more luck that it is not too distorted to be read than anything else.

**Comment by Sophist-UK** [comment]
@cstantech Found that on Windows 10 1703 onwards there is a compatibility setting for DPI issues. I will try this when I am back at my laptop, but you may also want to try it.

**Comment by Sophist-UK** [comment]
@SanderSade I hope I have given Khaled enough info about HighDPI support to engage his interest in supporting it properly.

**Comment by Sophist-UK** [comment]
@cstantech Please download and try code from https://raw.githubusercontent.com/DukeLupus/dlFilter/dialog-option-map/dlFilter.mrc to see if this fixes the issue without needing the compatibility settings above.

**Comment by Sophist-UK** [comment]
@cstantech Please respond within the next day or so - otherwise I will merge this regardless of whether it make your own situation better or worse

**Comment by Sophist-UK** [comment]
Since @cstantech didn't respond, I have now merged the fix for high resolution displays.
