### ISSUE TITLE
DLFilter Menu

### ISSUE THREAD

**Issue by DukeLupus** [DukeLupus/dlFilter#75]
Submitter: LawdyMama
Email: CatchMeOnIRCHighway#Ebooks@IRCHighwayEbooks.Net
Please reduce the amount of space the DLFilter uses in the menu.  For example, when right clicking in the channel, there are options for the following on the main:

dlfilter
Open onotice chat window
filter coloured messages
hide filter window(s)
hide ad window(s)
Options

It should be:
DLFilter (on right click)
-Options (on submenu, et al)
-Open ONotice Chat Window
-Show/Hide
--Filter Coloured Messages
--Hide Filter Windows
--Hide Ad Windows

**Comment by Sophist-UK** [comment]
Is that a hint? ;-)

**Comment by SanderSade** [comment]
Indeed. Duchess is unhappy ;)
