### ISSUE TITLE
Invalid parameters error

### ISSUE THREAD

**Issue by danj2k** [DukeLupus/dlFilter#76]
I'm getting a whole bunch of:

/set: invalid parameters (line 1070, DLFilter.mrc)

errors after updating to version 2.08.

mIRC version is 7.52.

**Comment by Sophist-UK** [comment]
Fixed yesterday in fdf9f06c51e190d72f420793bc936ecf88cd4af7 - so will be fixed in the next release.

However if you fancy testing this and giving feedback then if you download DLF from https://raw.githubusercontent.com/DukeLupus/dlFilter/master/dlFilter.mrc it should be fixed.

**Comment by danj2k** [comment]
That's got it. Thanks.

**Comment by danj2k** [comment]
After restarting mIRC everything looks ok, I will keep an eye on it and see if the error comes back again.

**Comment by Sophist-UK** [comment]
Sorry - my original fix didn't fix it. But I do believe that it ***is*** now fixed if you download it again.

**Comment by danj2k** [comment]
OK, trying it again (the problem did return eventually)
