### ISSUE TITLE
I load the script and nothing happens other than mIRC warning me not to click Yes. 

### ISSUE THREAD

**Issue by DukeLupus** [DukeLupus/dlFilter#78]
Submitter: Ken 
Email: new_2_va_2003@hotmail.com
Nothing happens when I try to load the script in an mIRC window.

**Comment by SanderSade** [comment]
What happens when you click Yes? You should get more loading information in the status window, at least?

Also, what version of mIRC and dlFilter?

**Comment by Sophist-UK** [comment]
No point in asking here for a report made via gitreports - as OP will not be notified. Did you ask him by email also?

**Comment by Sophist-UK** [comment]
Closing as no further information and not able to reproduce.
