### ISSUE TITLE
fltered my own  typing to  server window 

### ISSUE THREAD

**Issue by DukeLupus** [DukeLupus/dlFilter#79]
Submitter: quietsilence
Email: quietsilence@gmail.com
every thing i type in a chan   is repeated in the  main network chan 
DFLT ParseOut PRIVMSG #pirates :p sail Santiago
DFLT ParseOut PRIVMSG #pirates :p chest
DFLT ParseOut PRIVMSG #pirates :p use 181
DFLT ParseOut PRIVMSG DragonRyder :not done yet
DFLT ParseOut PRIVMSG DragonRyder :prob be tomarow
DFLT ParseOut PRIVMSG DragonRyder :im not feeling well
DFLT ParseOut PRIVMSG DragonRyder :sry
DFLT ParseOut PRIVMSG #pirates :p dive
DFLT ParseOut PRIVMSG DragonRyder :thanx
[14:12] [dlFilter] Running current version of dlFilter.
i also just noticed that  private chat is also doing the same thing just my side of the convo

**Comment by Sophist-UK** [comment]
Its a debug message I forgot to remove.

**Comment by Sophist-UK** [comment]
Fixed on 4 Jun and in release issued on 29 Jul.
