### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by SanderSade** [DukeLupus/dlFilter#8]
More in-depth readme, with screenshots and usage details. GH should become the main "home" for the script.

I'll do it together with vNext release.

**Comment by SanderSade** [comment]
> Also, when you rewrite the ReadMe, can we add some guidelines on the information we need to receive if someone raises a support issue.

**Comment by Sophist-UK** [comment]
I have updated. @SanderSade can you please review and confirm you are happy with it.

**Comment by SanderSade** [comment]
- Please hide (blur) the nicks in the channel screenshot
- Some screenshots of the options 
- Some screenshots of the dlf. windows with explanations would be good
- some explanation of the options would be good, as even I find some of them unclear...
