### ISSUE TITLE
mirc lockup with dlfilter

### ISSUE THREAD

**Issue by DukeLupus** [DukeLupus/dlFilter#80]
Submitter: Shawn
Email: nanoflower@gmail.com
I started running dlfilter yesterday and while it's a nice program I'm running in to an issue where it seems to be causing
mIRC to lockup. After about two hours of running it in the #ebooks (irchighway) channel mirc locksup hard. It's happened
multiple times. If I turn off dlfilter there are no lockups. I am running dlfilter 2.09 and mircsearcher on mirc 7.55. Those are
the only scripts I'm running.  It's not a memory issue going by task manager so I'm not sure what is happening. This is on Windows 10.

**Comment by Sophist-UK** [comment]
User had modified the mircSearch script and that was what was causing lockups.
