### ISSUE TITLE
Please create a tutorial on how to make dlls for mirc using latest IDE's like VS 2019.

### ISSUE THREAD

**Issue by roboirc** [DukeLupus/dlFilter#83]
Please create a tutorial on how to make dlls for mirc using latest IDE's like VS 2019 etc
Thanks!

**Comment by Sophist-UK** [comment]
dlFilter doesn't use such dlls. Sorry.

However I believe that there are some ancient tutorials elsewhere on the Internet. If you find what you want please post here. 

P. S. If you are interested in joining a new initiative to give mirc scripting an entirely new lease of life, please post your email address or drop me a line.
