### ISSUE TITLE
Where is version 2.12?

### ISSUE THREAD

**Issue by DukeLupus** [DukeLupus/dlFilter#86]
Submitter: Ed Greer
Email: edgreer666@gmail.com
I'm using dlFilter with mIRC.
Lately, I'm being bombarded by notices that I need to upgrade to dlFilter version 2.12.
But the link in the messages directs me to github.com/DukeLupus/dlFilter,  where the latest version I see is version 2.11
????????????

**Comment by Sophist-UK** [comment]
Oops.

Thank you for pointing this out to me. I fixed it when I was away on a business trip - but forgot to create the release.
