### ISSUE TITLE
No AppData message on installation  of 2.12

### ISSUE THREAD

**Issue by DukeLupus** [DukeLupus/dlFilter#87]
Submitter: Dad
Email: andyk_00@yahoo.com
Getting message:
 * /load: no such file 'C:\Users\Dad\AppData\Roaming\mIRC\dlFilter.mrc'

**Comment by Sophist-UK** [comment]
It is unclear whether this is a message to typing the /load or whether this is a bug in dlFilter.

If dlFilter is giving this error message, then it could be a bug. I have made a minor fix with commit 9457b2ac2fc6a5674cf74b15b923ff0bc3a5dc50 and created v2.13 to address this.
